### ISSUE TITLE
Devop Message should include commit/build/version info

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops#3]
The deployment bot announces in the chat every deployment in the staging swarm (i.e. osparc02) as
```
 New staging version of oSparc simcore core platform is available here !!!
```
It has a link to the websit but no information about what is new in this version.

As I user, I would like to have a link to
 a) what repo/commit/branch corresponds to this
 b) a history or feature list 

this way I can for instance ascertain e.g. whether a given bug fix or a given closed feature is actually online or not.

**Comment by sanderegg** [comment]
the deployment service shall:
- [ ] read the current sha of the deployed services (or read from the docker labels)
- [ ] read the sha of the new services
- [ ] do a git diff between the old sha and the new one on the git repo
- [ ] output the diff result in the notification

Bonus:
- [ ] if the deployer crashes it would be nice to notify as well
- [ ] if the deployer is re-started it would be nice to have a hint as well

**Comment by sanderegg** [comment]
the notifier now outputs the last sha of the deployed services.
