### ISSUE TITLE
Fix versions of services in osparc-ops and try renovatebot tool to update tools

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-ops#36]
shouldn't we fix a version and then have a bot that creates a branch, upgrades to latest version each image and run the tests automatically?? 

We should check tools like https://renovatebot.com/

_Originally posted by @pcrespov in https://github.com/ITISFoundation/osparc-ops/pull/33_

**Comment by pcrespov** [comment]
check if this has some usefule info you might want to follow upon, otherwise please just close. thx

**Comment by mrnicegyu11** [comment]
moved to new ops-repo
