### ISSUE TITLE
the deployer needs to be able to revert by version

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-ops#68]
currently the deployer cannot revert by one version easily

use-case:
- deployment done, the deployer uses the latest docker-compose on simcore repo + docker images marked as master-latest
- suddenly we need to revert to commit XXX

current workaround:
- change the variable SIMCORE_IMAGE_TAG to the the docker image needed
- manually change the docker-compose in portainer (very error prone process)

**Comment by pcrespov** [comment]
The deployer should be also able to deduce the correct image tag, provided a branch and a commit id. Notice that the tag are compositions of different fields:
https://hub.docker.com/r/itisfoundation/webserver/tags

**Comment by pcrespov** [comment]
Another issue regards the order in which the deployer sort the tags. This has an impact in which is the "latest" release tag.

use case:
 - by mistake, master HEAD is tagged as release 1.1
 - a correction tags stage HEAD as new release 1.2
 - commit tagged release 1.1 is *newer* than commit tagged release 1.2

so, you have that if you sort by date, then release 1.2 < 1.1 but if you sort by release number 1.1 < 1.2!

**Comment by pcrespov** [comment]
This could be REALLY handy to have in place, specially for critical moments like when a bad release reaches production

**Comment by mrnicegyu11** [comment]
moved to https://github.com/ITISFoundation/osparc-deployment-agent/issues/24
