### ISSUE TITLE
E2E testing and CI for ops

### ISSUE THREAD

**Issue by Surfict** [ITISFoundation/osparc-ops#71]
**USER STORY:**

Adding a CI that test automatically each service of the ops stack (For example, by logging at them) every 10 or 20 mns. This CI should also test the make-up local (local deployment when a new commit has been added on the repo.

**DEFINITION OF DONE:**

- Every 20 mns, a test of every services of the ops stack is done. If it failed, a mail is sent to the devops team.
- When a new commit is added to the depo, the CI test the make-up local command of the stack. If it failed, a mail is sent to the devops team.

**Comment by mrnicegyu11** [comment]
this is done
